[package]
name = "bifrostlink-ports"
description = "Transports for bifrostlink"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/bifrostlink-ports"
keywords = ["rpc", "async", "transport", "tokio", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
bifrostlink.workspace = true
bytes.workspace = true
tokio = { workspace = true, features = ["net", "io-std", "io-util"] }
tracing.workspace = true
